name: dlcv
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - pip 
    - numpy
    - tensorflow==2.0.0 # or tensorflow-gpu
    - scikit-image
    - pillow
    - imutils
    - scikit-learn
    - matplotlib
    - progressbar2
    - beautifulsoup4
    - pandas
    - pip:
        - opencv-contrib-python

